
class CountryCurrency {
  String country;
  String symbol;

  CountryCurrency(this.country, this.symbol);

  static List<CountryCurrency> getCurrencySymbol() {
    return <CountryCurrency> [
      CountryCurrency('Afghanistan', '؋'),
      CountryCurrency('Armenia', 'դր'),
      CountryCurrency('Azerbaijan', '₼'),
      CountryCurrency('Bahrain', '.د.ب '),
      CountryCurrency('Bangladesh', '৳'),
      CountryCurrency('Bhutan', 'Nu.'),
      CountryCurrency('Brunei', '\$'),
      CountryCurrency('Cambodia', '៛'),
      CountryCurrency('China', '¥'),
      CountryCurrency('Cyprus', '£'),
      CountryCurrency('Georgia', ' ლ'),
      CountryCurrency('India', '₹'),
      CountryCurrency('Indonesia', 'Rp'),
      CountryCurrency('Iran', '﷼'),
      CountryCurrency('Iraq', 'ع.د'),
      CountryCurrency('Israel', '₪'),
      CountryCurrency('Japan', '¥'),
      CountryCurrency('Jordan', 'د.ا'),
      CountryCurrency('Kazakhstan', 'лв'),
      CountryCurrency('Kuwait', 'د.ك '),
      CountryCurrency('Kyrgyzstan', 'лв'),
      CountryCurrency('Laos', '₭'),
      CountryCurrency('Lebanon', '£'),
      CountryCurrency('Malaysia', 'RM'),
      CountryCurrency('Maldives', 'Rf'),
      CountryCurrency('Mongolia', '₮'),
      CountryCurrency('Myanmar (Burma),', 'K'),
      CountryCurrency('Nepal', '₨'),
      CountryCurrency('North Korea', '₩'),
      CountryCurrency('Oman', '﷼'),
      CountryCurrency('Pakistan', '₨'),
      CountryCurrency('Palestine', 'د.ا'),
      CountryCurrency('Philippines', '₱'),
      CountryCurrency('Qatar', '﷼'),
      CountryCurrency('Russia', '₽'),
      CountryCurrency('Saudi Arabia', '﷼'),
      CountryCurrency('Singapore', '\$'),
      CountryCurrency('South Korea', '₩'),
      CountryCurrency('Sri Lanka', '₨'),
      CountryCurrency('Syria', '£'),
      CountryCurrency('Taiwan', 'NT\$'),
      CountryCurrency('Tajikistan', 'ЅM'),
      CountryCurrency('Thailand', '฿'),
      CountryCurrency('Timor-Leste', '\$'),
      CountryCurrency('Turkey', '₺'),
      CountryCurrency('Turkmenistan', 'T'),
      CountryCurrency('United Arab Emirates (UAE),', 'د.إ'),
      CountryCurrency('Uzbekistan', 'лв'),
      CountryCurrency('Vietnam', '₫'),
      CountryCurrency('Yemen', '﷼'),
      CountryCurrency('Country', 'Symbol'),
      CountryCurrency('Algeria', 'دج'),
      CountryCurrency('Angola', 'Kz'),
      CountryCurrency('Benin', 'CFA'),
      CountryCurrency('Botswana', 'P'),
      CountryCurrency('Burkina Faso', 'CFA'),
      CountryCurrency('Burundi', 'FBu'),
      CountryCurrency('Cabo Verde', '\$'),
      CountryCurrency('Cameroon', 'FCFA'),
      CountryCurrency('Central African Republic (CAR),', 'FCFA'),
      CountryCurrency('Chad', 'FCFA'),
      CountryCurrency('Comoros', 'CF'),
      CountryCurrency('Democratic Republic of the Congo', 'FC'),
      CountryCurrency('Republic of the Congo', 'FCFA'),
      CountryCurrency('Cote d\'Ivoire', 'CFA'),
      CountryCurrency('Djibouti', 'Fdj'),
      CountryCurrency('Egypt', '£'),
      CountryCurrency('Equatorial Guinea', 'FCFA'),
      CountryCurrency('Eritrea', 'ናቕፋ'),
      CountryCurrency('Ethiopia', 'ብር'),
      CountryCurrency('Gabon', 'FCFA'),
      CountryCurrency('Gambia', 'D'),
      CountryCurrency('Ghana', 'GH₵'),
      CountryCurrency('Guinea', 'FG'),
      CountryCurrency('Guinea-Bissau', 'CFA'),
      CountryCurrency('Kenya', 'KSh,'),
      CountryCurrency('Lesotho', 'L '),
      CountryCurrency('Liberia', '\$'),
      CountryCurrency('Libya', 'ل.د'),
      CountryCurrency('Madagascar', 'Ar'),
      CountryCurrency('Malawi', 'MK'),
      CountryCurrency('Mali', 'CFA'),
      CountryCurrency('Mauritania', 'UM'),
      CountryCurrency('Mauritius', '₨'),
      CountryCurrency('Morocco', 'DH'),
      CountryCurrency('Mozambique', 'MT'),
      CountryCurrency('Namibia', '\$'),
      CountryCurrency('Niger', 'CFA'),
      CountryCurrency('Nigeria', '₦'),
      CountryCurrency('Rwanda', 'FRw'),
      CountryCurrency('Sao Tome and Principe', ' Db'),
      CountryCurrency('Senegal', 'CFA'),
      CountryCurrency('Seychelles', '₨'),
      CountryCurrency('Sierra Leone', 'Le'),
      CountryCurrency('Somalia', 'S'),
      CountryCurrency('South Africa', 'R'),
      CountryCurrency('South Sudan', '£'),
      CountryCurrency('Sudan', 'SD'),
      CountryCurrency('Swaziland', 'E '),
      CountryCurrency('Tanzania', 'TSh'),
      CountryCurrency('Togo', 'CFA'),
      CountryCurrency('Tunisia', 'د.ت'),
      CountryCurrency('Uganda', 'USh'),
      CountryCurrency('Zambia', 'ZK'),
      CountryCurrency('Zimbabwe', '\$'),
      CountryCurrency('Country', 'Symbol'),
      CountryCurrency('Albania', 'Lek'),
      CountryCurrency('Andorra', '€'),
      CountryCurrency('Armenia', 'դր.'),
      CountryCurrency('Austria', '€'),
      CountryCurrency('Azerbaijan', '₼'),
      CountryCurrency('Belarus', 'Br'),
      CountryCurrency('Belgium', '€'),
      CountryCurrency('Bosnia and Herzegovina', 'KM'),
      CountryCurrency('Bulgaria', 'лв'),
      CountryCurrency('Croatia', 'kn'),
      CountryCurrency('Cyprus', '£'),
      CountryCurrency('Czech Republic', 'Kč'),
      CountryCurrency('Denmark', 'kr.'),
      CountryCurrency('Estonia', 'EEK'),
      CountryCurrency('Finland', '€'),
      CountryCurrency('France', '€'),
      CountryCurrency('Georgia', 'ლ'),
      CountryCurrency('Germany', '€'),
      CountryCurrency('Greece', '€'),
      CountryCurrency('Hungary', 'Ft'),
      CountryCurrency('Iceland', 'kr'),
      CountryCurrency('Ireland', '€'),
      CountryCurrency('Italy', '€'),
      CountryCurrency('Kazakhstan', 'лв'),
      CountryCurrency('Kosovo', '€'),
      CountryCurrency('Latvia', 'Ls'),
      CountryCurrency('Liechtenstein', 'CHF'),
      CountryCurrency('Lithuania', 'Lt '),
      CountryCurrency('Luxembourg', '€'),
      CountryCurrency('Macedonia (FYROM),', 'ден'),
      CountryCurrency('Malta', '₤'),
      CountryCurrency('Moldova', 'L'),
      CountryCurrency('Monaco', '€'),
      CountryCurrency('Montenegro', '€'),
      CountryCurrency('Netherlands', '€'),
      CountryCurrency('Norway', 'kr'),
      CountryCurrency('Poland', 'zł'),
      CountryCurrency('Portugal', '€'),
      CountryCurrency('Romania', 'lei'),
      CountryCurrency('Russia', '₽'),
      CountryCurrency('San Marino', '€'),
      CountryCurrency('Serbia', 'Дин.'),
      CountryCurrency('Slovakia', 'Sk'),
      CountryCurrency('Slovenia', '€'),
      CountryCurrency('Spain', '€'),
      CountryCurrency('Sweden', 'kr'),
      CountryCurrency('Switzerland', 'CHF'),
      CountryCurrency('Turkey', '₺'),
      CountryCurrency('Ukraine', '₴'),
      CountryCurrency('United Kingdom (UK),', '£'),
      CountryCurrency('Vatican City (Holy See),', '€'),
      CountryCurrency('Country', 'Symbol'),
      CountryCurrency('Antigua and Barbuda', '\$'),
      CountryCurrency('Bahamas', '\$'),
      CountryCurrency('Barbados', '\$'),
      CountryCurrency('Belize', 'BZ\$'),
      CountryCurrency('Canada', '\$'),
      CountryCurrency('Costa Rica', '₡'),
      CountryCurrency('Cuba', '\$'),
      CountryCurrency('Dominica', '\$'),
      CountryCurrency('Dominican Republic', 'RD\$'),
      CountryCurrency('El Salvador', '\$'),
      CountryCurrency('Grenada', '\$'),
      CountryCurrency('Guatemala', 'Q'),
      CountryCurrency('Haiti', 'G'),
      CountryCurrency('Honduras', 'L'),
      CountryCurrency('Jamaica', 'J\$'),
      CountryCurrency('Mexico', '\$'),
      CountryCurrency('Nicaragua', 'C\$'),
      CountryCurrency('Panama', 'B/.'),
      CountryCurrency('Saint Kitts and Nevis', '\$'),
      CountryCurrency('Saint Lucia', '\$'),
      CountryCurrency('Saint Vincent and the Grenadines', '\$'),
      CountryCurrency('Trinidad and Tobago', 'TT\$'),
      CountryCurrency('United States of America (USA),', '\$'),
      CountryCurrency('Country', 'Symbol'),
      CountryCurrency('Argentina', '\$'),
      CountryCurrency('Bolivia', '\$b'),
      CountryCurrency('Brazil', 'R\$'),
      CountryCurrency('Chile', '\$'),
      CountryCurrency('Colombia', '\$'),
      CountryCurrency('Ecuador', '\$'),
      CountryCurrency('Guyana', '\$'),
      CountryCurrency('Paraguay', 'Gs'),
      CountryCurrency('Peru', 'S/.'),
      CountryCurrency('Suriname', '\$'),
      CountryCurrency('Uruguay', '\$U'),
      CountryCurrency('Venezuela', 'Bs'),
      CountryCurrency('Country', 'Symbol'),
      CountryCurrency('Australia', '\$'),
      CountryCurrency('Fiji', '\$'),
      CountryCurrency('Kiribati', '\$'),
      CountryCurrency('Marshall Islands', '\$'),
      CountryCurrency('Micronesia', '\$'),
      CountryCurrency('Nauru', '\$'),
      CountryCurrency('New Zealand', '\$'),
      CountryCurrency('Palau', '\$'),
      CountryCurrency('Papua New Guinea', 'K'),
      CountryCurrency('Samoa', 'WS\$'),
      CountryCurrency('Solomon Islands', '\$'),
      CountryCurrency('Tonga', 'T\$'),
      CountryCurrency('Tuvalu', '\$'),
    ];
  }
}