
import 'package:hive/hive.dart';
part 'country_currency_model.g.dart';

@HiveType(typeId: 15, adapterName: 'CountryCurrencyAdapter')
class CountryCurrency extends HiveObject {

  @HiveField(0)
  String country;

  @HiveField(1)
  String symbol;

  CountryCurrency({this.country, this.symbol});

  static List<CountryCurrency> getCurrencySymbol() {
    return <CountryCurrency> [
      CountryCurrency(country: 'Afghanistan', symbol:'؋'),
      CountryCurrency(country: 'Armenia', symbol:'դր'),
      CountryCurrency(country: 'Azerbaijan', symbol:'₼'),
      CountryCurrency(country: 'Bahrain', symbol:'.د.ب '),
      CountryCurrency(country: 'Bangladesh', symbol:'৳'),
      CountryCurrency(country: 'Bhutan', symbol:'Nu.'),
      CountryCurrency(country: 'Brunei', symbol:'\$'),
      CountryCurrency(country: 'Cambodia', symbol:'៛'),
      CountryCurrency(country: 'China', symbol:'¥'),
      CountryCurrency(country: 'Cyprus', symbol:'£'),
      CountryCurrency(country: 'Georgia', symbol:' ლ'),
      CountryCurrency(country: 'India', symbol:'₹'),
      CountryCurrency(country: 'Indonesia', symbol:'Rp'),
      CountryCurrency(country: 'Iran', symbol:'﷼'),
      CountryCurrency(country: 'Iraq', symbol:'ع.د'),
      CountryCurrency(country: 'Israel', symbol:'₪'),
      CountryCurrency(country: 'Japan', symbol:'¥'),
      CountryCurrency(country: 'Jordan', symbol:'د.ا'),
      CountryCurrency(country: 'Kazakhstan', symbol:'лв'),
      CountryCurrency(country: 'Kuwait', symbol:'د.ك '),
      CountryCurrency(country: 'Kyrgyzstan', symbol:'лв'),
      CountryCurrency(country: 'Laos', symbol:'₭'),
      CountryCurrency(country: 'Lebanon', symbol:'£'),
      CountryCurrency(country: 'Malaysia', symbol:'RM'),
      CountryCurrency(country: 'Maldives', symbol:'Rf'),
      CountryCurrency(country: 'Mongolia', symbol:'₮'),
      CountryCurrency(country: 'Myanmar (Burma),', symbol:'K'),
      CountryCurrency(country: 'Nepal', symbol:'₨'),
      CountryCurrency(country: 'North Korea', symbol:'₩'),
      CountryCurrency(country: 'Oman', symbol:'﷼'),
      CountryCurrency(country: 'Pakistan', symbol:'₨'),
      CountryCurrency(country: 'Palestine', symbol:'د.ا'),
      CountryCurrency(country: 'Philippines', symbol:'₱'),
      CountryCurrency(country: 'Qatar', symbol:'﷼'),
      CountryCurrency(country: 'Russia', symbol:'₽'),
      CountryCurrency(country: 'Saudi Arabia', symbol:'﷼'),
      CountryCurrency(country: 'Singapore', symbol:'\$'),
      CountryCurrency(country: 'South Korea', symbol:'₩'),
      CountryCurrency(country: 'Sri Lanka', symbol:'₨'),
      CountryCurrency(country: 'Syria', symbol:'£'),
      CountryCurrency(country: 'Taiwan', symbol:'NT\$'),
      CountryCurrency(country: 'Tajikistan', symbol:'ЅM'),
      CountryCurrency(country: 'Thailand', symbol:'฿'),
      CountryCurrency(country: 'Timor-Leste', symbol:'\$'),
      CountryCurrency(country: 'Turkey', symbol:'₺'),
      CountryCurrency(country: 'Turkmenistan', symbol:'T'),
      CountryCurrency(country: 'United Arab Emirates (UAE),', symbol:'د.إ'),
      CountryCurrency(country: 'Uzbekistan', symbol:'лв'),
      CountryCurrency(country: 'Vietnam', symbol:'₫'),
      CountryCurrency(country: 'Yemen', symbol:'﷼'),
      CountryCurrency(country: 'Country', symbol:'Symbol'),
      CountryCurrency(country: 'Algeria', symbol:'دج'),
      CountryCurrency(country: 'Angola', symbol:'Kz'),
      CountryCurrency(country: 'Benin', symbol:'CFA'),
      CountryCurrency(country: 'Botswana', symbol:'P'),
      CountryCurrency(country: 'Burkina Faso', symbol:'CFA'),
      CountryCurrency(country: 'Burundi', symbol:'FBu'),
      CountryCurrency(country: 'Cabo Verde', symbol:'\$'),
      CountryCurrency(country: 'Cameroon', symbol:'FCFA'),
      CountryCurrency(country: 'Central African Republic (CAR),', symbol:'FCFA'),
      CountryCurrency(country: 'Chad', symbol:'FCFA'),
      CountryCurrency(country: 'Comoros', symbol:'CF'),
      CountryCurrency(country: 'Democratic Republic of the Congo', symbol:'FC'),
      CountryCurrency(country: 'Republic of the Congo', symbol:'FCFA'),
      CountryCurrency(country: 'Cote d\'Ivoire', symbol:'CFA'),
      CountryCurrency(country: 'Djibouti', symbol:'Fdj'),
      CountryCurrency(country: 'Egypt', symbol:'£'),
      CountryCurrency(country: 'Equatorial Guinea', symbol:'FCFA'),
      CountryCurrency(country: 'Eritrea', symbol:'ናቕፋ'),
      CountryCurrency(country: 'Ethiopia', symbol:'ብር'),
      CountryCurrency(country: 'Gabon', symbol:'FCFA'),
      CountryCurrency(country: 'Gambia', symbol:'D'),
      CountryCurrency(country: 'Ghana', symbol:'GH₵'),
      CountryCurrency(country: 'Guinea', symbol:'FG'),
      CountryCurrency(country: 'Guinea-Bissau', symbol:'CFA'),
      CountryCurrency(country: 'Kenya', symbol:'KSh,'),
      CountryCurrency(country: 'Lesotho', symbol:'L '),
      CountryCurrency(country: 'Liberia', symbol:'\$'),
      CountryCurrency(country: 'Libya', symbol:'ل.د'),
      CountryCurrency(country: 'Madagascar', symbol:'Ar'),
      CountryCurrency(country: 'Malawi', symbol:'MK'),
      CountryCurrency(country: 'Mali', symbol:'CFA'),
      CountryCurrency(country: 'Mauritania', symbol:'UM'),
      CountryCurrency(country: 'Mauritius', symbol:'₨'),
      CountryCurrency(country: 'Morocco', symbol:'DH'),
      CountryCurrency(country: 'Mozambique', symbol:'MT'),
      CountryCurrency(country: 'Namibia', symbol:'\$'),
      CountryCurrency(country: 'Niger', symbol:'CFA'),
      CountryCurrency(country: 'Nigeria', symbol:'₦'),
      CountryCurrency(country: 'Rwanda', symbol:'FRw'),
      CountryCurrency(country: 'Sao Tome and Principe', symbol:' Db'),
      CountryCurrency(country: 'Senegal', symbol:'CFA'),
      CountryCurrency(country: 'Seychelles', symbol:'₨'),
      CountryCurrency(country: 'Sierra Leone', symbol:'Le'),
      CountryCurrency(country: 'Somalia', symbol:'S'),
      CountryCurrency(country: 'South Africa', symbol:'R'),
      CountryCurrency(country: 'South Sudan', symbol:'£'),
      CountryCurrency(country: 'Sudan', symbol:'SD'),
      CountryCurrency(country: 'Swaziland', symbol:'E '),
      CountryCurrency(country: 'Tanzania', symbol:'TSh'),
      CountryCurrency(country: 'Togo', symbol:'CFA'),
      CountryCurrency(country: 'Tunisia', symbol:'د.ت'),
      CountryCurrency(country: 'Uganda', symbol:'USh'),
      CountryCurrency(country: 'Zambia', symbol:'ZK'),
      CountryCurrency(country: 'Zimbabwe', symbol:'\$'),
      CountryCurrency(country: 'Country', symbol:'Symbol'),
      CountryCurrency(country: 'Albania', symbol:'Lek'),
      CountryCurrency(country: 'Andorra', symbol:'€'),
      CountryCurrency(country: 'Armenia', symbol:'դր.'),
      CountryCurrency(country: 'Austria', symbol:'€'),
      CountryCurrency(country: 'Azerbaijan', symbol:'₼'),
      CountryCurrency(country: 'Belarus', symbol:'Br'),
      CountryCurrency(country: 'Belgium', symbol:'€'),
      CountryCurrency(country: 'Bosnia and Herzegovina', symbol:'KM'),
      CountryCurrency(country: 'Bulgaria', symbol:'лв'),
      CountryCurrency(country: 'Croatia', symbol:'kn'),
      CountryCurrency(country: 'Cyprus', symbol:'£'),
      CountryCurrency(country: 'Czech Republic', symbol:'Kč'),
      CountryCurrency(country: 'Denmark', symbol:'kr.'),
      CountryCurrency(country: 'Estonia', symbol:'EEK'),
      CountryCurrency(country: 'Finland', symbol:'€'),
      CountryCurrency(country: 'France', symbol:'€'),
      CountryCurrency(country: 'Georgia', symbol:'ლ'),
      CountryCurrency(country: 'Germany', symbol:'€'),
      CountryCurrency(country: 'Greece', symbol:'€'),
      CountryCurrency(country: 'Hungary', symbol:'Ft'),
      CountryCurrency(country: 'Iceland', symbol:'kr'),
      CountryCurrency(country: 'Ireland', symbol:'€'),
      CountryCurrency(country: 'Italy', symbol:'€'),
      CountryCurrency(country: 'Kazakhstan', symbol:'лв'),
      CountryCurrency(country: 'Kosovo', symbol:'€'),
      CountryCurrency(country: 'Latvia', symbol:'Ls'),
      CountryCurrency(country: 'Liechtenstein', symbol:'CHF'),
      CountryCurrency(country: 'Lithuania', symbol:'Lt '),
      CountryCurrency(country: 'Luxembourg', symbol:'€'),
      CountryCurrency(country: 'Macedonia (FYROM),', symbol:'ден'),
      CountryCurrency(country: 'Malta', symbol:'₤'),
      CountryCurrency(country: 'Moldova', symbol:'L'),
      CountryCurrency(country: 'Monaco', symbol:'€'),
      CountryCurrency(country: 'Montenegro', symbol:'€'),
      CountryCurrency(country: 'Netherlands', symbol:'€'),
      CountryCurrency(country: 'Norway', symbol:'kr'),
      CountryCurrency(country: 'Poland', symbol:'zł'),
      CountryCurrency(country: 'Portugal', symbol:'€'),
      CountryCurrency(country: 'Romania', symbol:'lei'),
      CountryCurrency(country: 'Russia', symbol:'₽'),
      CountryCurrency(country: 'San Marino', symbol:'€'),
      CountryCurrency(country: 'Serbia', symbol:'Дин.'),
      CountryCurrency(country: 'Slovakia', symbol:'Sk'),
      CountryCurrency(country: 'Slovenia', symbol:'€'),
      CountryCurrency(country: 'Spain', symbol:'€'),
      CountryCurrency(country: 'Sweden', symbol:'kr'),
      CountryCurrency(country: 'Switzerland', symbol:'CHF'),
      CountryCurrency(country: 'Turkey', symbol:'₺'),
      CountryCurrency(country: 'Ukraine', symbol:'₴'),
      CountryCurrency(country: 'United Kingdom (UK),', symbol:'£'),
      CountryCurrency(country: 'Vatican City (Holy See),', symbol:'€'),
      CountryCurrency(country: 'Country', symbol:'Symbol'),
      CountryCurrency(country: 'Antigua and Barbuda', symbol:'\$'),
      CountryCurrency(country: 'Bahamas', symbol:'\$'),
      CountryCurrency(country: 'Barbados', symbol:'\$'),
      CountryCurrency(country: 'Belize', symbol:'BZ\$'),
      CountryCurrency(country: 'Canada', symbol:'\$'),
      CountryCurrency(country: 'Costa Rica', symbol:'₡'),
      CountryCurrency(country: 'Cuba', symbol:'\$'),
      CountryCurrency(country: 'Dominica', symbol:'\$'),
      CountryCurrency(country: 'Dominican Republic', symbol:'RD\$'),
      CountryCurrency(country: 'El Salvador', symbol:'\$'),
      CountryCurrency(country: 'Grenada', symbol:'\$'),
      CountryCurrency(country: 'Guatemala', symbol:'Q'),
      CountryCurrency(country: 'Haiti', symbol:'G'),
      CountryCurrency(country: 'Honduras', symbol:'L'),
      CountryCurrency(country: 'Jamaica', symbol:'J\$'),
      CountryCurrency(country: 'Mexico', symbol:'\$'),
      CountryCurrency(country: 'Nicaragua', symbol:'C\$'),
      CountryCurrency(country: 'Panama', symbol:'B/.'),
      CountryCurrency(country: 'Saint Kitts and Nevis', symbol:'\$'),
      CountryCurrency(country: 'Saint Lucia', symbol:'\$'),
      CountryCurrency(country: 'Saint Vincent and the Grenadines', symbol:'\$'),
      CountryCurrency(country: 'Trinidad and Tobago', symbol:'TT\$'),
      CountryCurrency(country: 'United States of America (USA)', symbol:'\$'),
      CountryCurrency(country: 'Country', symbol:'Symbol'),
      CountryCurrency(country: 'Argentina', symbol:'\$'),
      CountryCurrency(country: 'Bolivia', symbol:'\$b'),
      CountryCurrency(country: 'Brazil', symbol:'R\$'),
      CountryCurrency(country: 'Chile', symbol:'\$'),
      CountryCurrency(country: 'Colombia', symbol:'\$'),
      CountryCurrency(country: 'Ecuador', symbol:'\$'),
      CountryCurrency(country: 'Guyana', symbol:'\$'),
      CountryCurrency(country: 'Paraguay', symbol:'Gs'),
      CountryCurrency(country: 'Peru', symbol:'S/.'),
      CountryCurrency(country: 'Suriname', symbol:'\$'),
      CountryCurrency(country: 'Uruguay', symbol:'\$U'),
      CountryCurrency(country: 'Venezuela', symbol:'Bs'),
      CountryCurrency(country: 'Country', symbol:'Symbol'),
      CountryCurrency(country: 'Australia', symbol:'\$'),
      CountryCurrency(country: 'Fiji', symbol:'\$'),
      CountryCurrency(country: 'Kiribati', symbol:'\$'),
      CountryCurrency(country: 'Marshall Islands', symbol:'\$'),
      CountryCurrency(country: 'Micronesia', symbol:'\$'),
      CountryCurrency(country: 'Nauru', symbol:'\$'),
      CountryCurrency(country: 'New Zealand', symbol:'\$'),
      CountryCurrency(country: 'Palau', symbol:'\$'),
      CountryCurrency(country: 'Papua New Guinea', symbol:'K'),
      CountryCurrency(country: 'Samoa', symbol:'WS\$'),
      CountryCurrency(country: 'Solomon Islands', symbol:'\$'),
      CountryCurrency(country: 'Tonga', symbol:'T\$'),
      CountryCurrency(country: 'Tuvalu', symbol:'\$'),
    ];
  }
}